DROP TABLE IF EXISTS users;
CREATE TABLE users (
	id INTEGER PRIMARY KEY, 
	name VARCHAR(100) NOT NULL, 
	email VARCHAR(255) NOT NULL,  
	password VARCHAR(11) NOT NULL, 
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE errors_table (
	id INTEGER PRIMARY KEY, 
	level VARCHAR(100) NOT NULL, 
	description VARCHAR(255) NOT NULL, 
	log VARCHAR(500) NOT NULL, 
	origin VARCHAR(100) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);